### ISSUE TITLE
Transparent variants please

### ISSUE THREAD

**Issue by duganchen** [catppuccin/fzf#9]
May I please request variants that work well with translucent terminals? All it takes is removing the "bg" color. So, for example, mocha would become:

```
FZF_DEFAULT_OPTS="\
  --color=bg+:#313244,spinner:#f5e0dc,hl:#f38ba8 \
  --color=fg:#cdd6f4,header:#f38ba8,info:#cba6f7,pointer:#f5e0dc \
  --color=marker:#f5e0dc,fg+:#cdd6f4,prompt:#cba6f7,hl+:#f38ba8"
```

**Comment by sgoudham** [comment]
Hey :wave:, thanks for raising the issue.

Since it's quite trivial to make it work well with transparent terminals, I feel like it's better to add a note in the README instead of generating another code block for each shell with `bg` removed.
